Fix up short coming of DMD v2.111 or later with link error on windows
ser_build.obj : error LNK2019: unresolved external symbol __D4core8internal7switch___T14__switch_errorZQrFNaNbNiNfAyakZv referenced in function __D3std6format8internal6floats__T10printFloatTSQBs5array__T8AppenderTAyaZQoTdTaZQBvFNaNfKQBrxdSQDoQDn4spec__T10FormatSpecTaZQpZv

ser_build.exe : fatal error LNK1120: 1 unresolved externals

Error: linker exited with status 1120
       C:\Development\Microsoft\2022\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x86\link.exe /NOLOGO "ser_build\ser_build.obj"   /DEFAULTLIB:phobos32mscoff /DEBUG  /LIBPATH:"C:\Development\Microsoft\2022\Community\VC\Tools\MSVC\14.44.35207\lib\x86" legacy_stdio_definitions.lib /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\ucrt\x86" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.26100.0\um\x86"
Error: undefined reference to `pure nothrow @nogc @safe void core.internal.switch_.__switch_error!().__switch_error(immutable(char)[], uint)`
       referenced from `pure @safe void std.format.internal.floats.printFloat!(std.array.Appender!(immutable(char)[]).Appender, double, char).printFloat(ref std.array.Appender!(immutable(char)[]).Appender, const(double), std.format.spec.FormatSpec!(char).FormatSpec)`
       perhaps `.d` files need to be added on the command line, or use `-i` to compile imports